# configs/pipeline_cfg.yaml
io:
  video_source: "assets/test_meeting.mp4"
  # Để chạy camera laptop, đổi thành: video_source: 0

models:
  face_detector: "models/yolov8n-face.onnx"
  emotion_recognizer: "models/emotion-ferplus-12-int8.onnx"

params:
  smoothing_window: 10
  skip_frames: 2